### ISSUE TITLE
Request package names/applications to be added to lists

### ISSUE THREAD

**Issue by ZeroInfinityXDA** [Team-Helix/Helix-Engine-Dependencies#1]
Please write down in the comment section below what/which apps you want to be added and make sure to write what list they should belong to.

Battery apps: regular daily apps such as Facebook, Messenger, Whatsapp Instagram, Google Chrome etc. don't/shouldn't require that much processing power.

Balanced apps (these names do not go on either lists so don't bother requesting them as default will be balanced profile): Snapchat, Youtube, Netflix, Spotify, TIDAL, Phonograph, etc.

Performance apps: 3D games, 2D games, Camera apps (NOT like Snapchat), TitaniumBackup/Backup utility apps, File Explorer apps, Benchmarking apps, video editing/photo editing apps, apps that require a lot of processing power.

Whitelist: ignore apps so no scripts are executed whenever these apps open (e.g. SystemUI).

Background: Should be package names taken from performance apps, only apply to performance apps that may run heavy tasks in the background when the screen is off (e.g. TitaniumBackup for creating backups of large data, Copying/extracting/compressing large files in file explorers, exporting media from video editors or even photo editors).

NOTE: A thumbs up reaction to your comment means I have added them to the lists :)

**Comment by chotchot** [comment]
battery apps (folio, my digi, wechat,shopee ) 
balance (taobao/淘宝, pleco) 
performance (ro idle porings, google maps, swift backup)

**Comment by ZeroInfinityXDA** [comment]
@chotchot Folio, wechat, google maps, swift backup added, could you get me the package names (by looking at the end of the url in the play store app page) or link me to play store links for my digi, shopee, and ro idle porings please? Some of these apps have similar names to each other so it's difficult to make out which is the right one :) Also no need to request balanced apps as they will use balanced mode when they are not in either of the lists ;)

**Comment by chotchot** [comment]
1.https://play.google.com/store/apps/details?id=com.digi.portal.mobdev.android
2.https://play.google.com/store/apps/details?id=com.shopee.my
3.https://play.google.com/store/apps/details?id=com.gravity.poring.and
4.https://play.google.com/store/apps/details?id=com.creativetrends.folio.app (this is the new folio, because folio has new app but same name, and batery profile for this app) 

thanks dev for listening, really love your work, thank you for your hardwork, :3

**Comment by ychoon94** [comment]
1. https://play.google.com/store/apps/details?id=com.madhead.tos.zh (performance mode)
2. https://play.google.com/store/apps/details?id=com.square_enix.android_google.ffxvpe (performance mode)
3. https://play.google.com/store/apps/details?id=arun.com.chromer (battery saver)
4. https://play.google.com/store/apps/details?id=com.shahid.nid (battery saver)

 Thank you for your hard work :) loving the helix kernel for the OP5, hopefully it will be back up for oreo soon together with RZ kernel :)

**Comment by shawngeneticfreak** [comment]
Battery profile:
com.waze
com.google.android.gm
com.dropbox.paper
com.microsoft.office.outlook
com.spotify.music

**Comment by Pipodi** [comment]
Battery profile:
tv.twitch.android.app
com.google.android.youtube

**Comment by ghost** [comment]
Whitelist:

com.google.android.GCMODs5

**Comment by gershee** [comment]
whitelist the default oxygen camera app..
I'm having severe stuttering..

**Comment by ZeroInfinityXDA** [comment]
@gershee You mean add it to the performance profile? Whitelisting apps makes Helix Engine ignore it and I don't think you want that because, say for example you were on messenger and it executes battery profile, whitelisting camera makes Helix Engine ignore it and thus, ignores profile change (and will stay on battery profile). Adding it to the performance profile will make Helix Engine execute the performance profile when the app is detected.

Wait for beta 5 because there's a huge update incoming regarding app lists, and I think everyone will be surprised.

**Comment by ZeroInfinityXDA** [comment]
I will be closing this, as the upcoming beta 5 will allow users to add their own apps from the app itself.
